bind_addr = ":8080"
log_level = "debug"
database_url = "postgres://postgres:postgrespw@localhost:32768/testdb?sslmode=disable"
session_key = "QfTjWnZr4u7x!A%D*G-KaNdRgUkXp2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2s5v8y/B?E(H+MbQeThWmZq4t6w9z$C&"